apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: damian.wojciech@gmail.com
    privateKeySecretRef:
      name: cert-manager
    solvers:
      - http01:
          ingress:
            class: traefik
