apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:1.105.4
          ports:
            - containerPort: 5678
          env:
            - name: GENERIC_TIMEZONE
              value: 'Europe/Warsaw'
            - name: N8N_PROTOCOL
              value: 'https'
            - name: N8N_HOST
              value: 'ns3098488.ip-54-36-172.eu'
            - name: N8N_PORT
              value: '5678'
            - name: WEBHOOK_URL
              value: 'https://ns3098488.ip-54-36-172.eu:8443/'
            - name: N8N_BASIC_AUTH_ACTIVE
              value: 'true'
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-auth
                  key: username
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-auth
                  key: password
          resources:
            requests:
              cpu: '500m'
              memory: '512Mi'
            limits:
              cpu: '1'
              memory: '1Gi'
          volumeMounts:
            - name: n8n-storage
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-storage
          persistentVolumeClaim:
            claimName: n8n-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
spec:
  selector:
    app: n8n
  ports:
    - port: 80
      targetPort: 5678
