apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: platform
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://github.com/outsider255/gitops-root.git
    targetRevision: main
    path: apps/cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - SyncWave=1
