apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asset-library
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: render-service
  source:
    repoURL: https://github.com/outsider255/gitops-root.git
    targetRevision: main
    path: apps/asset-library
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
