apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgresql
  namespace: { { .Values.namespace } }
spec:
  selector:
    app: keycloak-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
