apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: { { .Values.namespace } }
spec:
  replicas: { { .Values.keycloak.replicas } }
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ['start-dev']
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: { { .Values.keycloak.adminUser | quote } }
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: { { .Values.keycloak.adminPassword | quote } }
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value:
                jdbc:postgresql://{{ .Values.externalDatabase.host }}:{{
                .Values.externalDatabase.port }}/{{
                .Values.externalDatabase.database }}
            - name: KC_DB_USERNAME
              value: { { .Values.externalDatabase.user | quote } }
            - name: KC_DB_PASSWORD
              value: { { .Values.externalDatabase.password | quote } }
