apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgresql
  namespace: keycloak
  labels:
    app: keycloak-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgresql
  template:
    metadata:
      labels:
        app: keycloak-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: keycloak-db
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          # Proste healthchecki
          readinessProbe:
            exec:
              command:
                ['sh', '-c', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                ['sh', '-c', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: keycloak-postgresql-pvc
