apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aurastream-media
  namespace: aurastream
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
