apiVersion: v1
kind: ServiceAccount
metadata:
  name: render-service-sa
  namespace: render-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: render-service-job-dispatcher
  namespace: render-service
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: render-service-job-dispatcher-binding
  namespace: render-service
subjects:
  - kind: ServiceAccount
    name: render-service-sa
    namespace: render-service
roleRef:
  kind: Role
  name: render-service-job-dispatcher
  apiGroup: rbac.authorization.k8s.io
