apiVersion: v1
kind: ServiceAccount
metadata:
  name: zitadel-runtime
  namespace: zitadel
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zitadel-login
  namespace: zitadel
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: false
