apiVersion: v1
kind: Service
metadata:
  name: dotnet-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: dotnet-api
  ports:
    - protocol: TCP
      port: {{ .Values.dotnetApp.servicePort }}
      targetPort: {{ .Values.dotnetApp.containerPort }}