apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: {{ .Values.sqlserver.password | quote }}
          resources:
            limits:
              memory: {{ .Values.sqlserver.memoryLimit }}
              cpu: {{ .Values.sqlserver.cpuLimit }}